<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ $title ?? 'Report' }}</title>
    <style>
        @font-face {
            font-family: 'Inter';
            font-weight: 400;
            src: url(https://cdn.jsdelivr.net/npm/@fontsource/inter@4.5.15/files/inter-latin-400-normal.woff) format('woff');
        }
        @font-face {
            font-family: 'Inter';
            font-weight: 600;
            src: url(https://cdn.jsdelivr.net/npm/@fontsource/inter@4.5.15/files/inter-latin-600-normal.woff) format('woff');
        }
        @font-face {
            font-family: 'Inter';
            font-weight: 700;
            src: url(https://cdn.jsdelivr.net/npm/@fontsource/inter@4.5.15/files/inter-latin-700-normal.woff) format('woff');
        }
        @font-face {
            font-family: 'Inter';
            font-weight: 800;
            src: url(https://cdn.jsdelivr.net/npm/@fontsource/inter@4.5.15/files/inter-latin-800-normal.woff) format('woff');
        }
        @page { margin: 0; }
        * { margin: 0; padding: 0; box-sizing: border-box; }
        body { font-family: 'Inter', 'Helvetica', sans-serif; color: #0f172a; font-size: 10pt; line-height: 1.5; }
        .band { background: #4b8eff; height: 8px; }
        .container { padding: 30px 40px; }
        .header { width: 100%; margin-bottom: 24px; }
        .header td { vertical-align: top; }
        .brand { font-size: 18pt; font-weight: 800; color: #4b8eff; }
        .brand-meta { color: #64748b; font-size: 9pt; margin-top: 2px; }
        .report-meta { text-align: right; }
        .report-label { font-size: 8.5pt; font-weight: 700; text-transform: uppercase; letter-spacing: 1.4pt; color: #94a3b8; }
        .report-title { font-size: 16pt; font-weight: 800; margin-top: 4px; }
        .report-range { color: #64748b; font-size: 9pt; margin-top: 4px; }

        .kpi-row { width: 100%; margin-bottom: 22px; }
        .kpi { background: #f8fafc; border: 1px solid #e2e8f0; border-radius: 8px; padding: 12px 14px; }
        .kpi-label { font-size: 8.5pt; text-transform: uppercase; letter-spacing: 1pt; color: #94a3b8; font-weight: 700; }
        .kpi-value { font-size: 15pt; font-weight: 800; color: #0f172a; margin-top: 4px; }
        .kpi-sub { font-size: 8.5pt; color: #64748b; margin-top: 2px; }

        .section-title { font-size: 9pt; text-transform: uppercase; letter-spacing: 1.4pt; color: #94a3b8; font-weight: 800; margin: 18px 0 8px 0; padding-bottom: 4px; border-bottom: 1px solid #e2e8f0; }

        table.data { width: 100%; border-collapse: collapse; margin-bottom: 12px; }
        table.data th { text-align: left; font-size: 8.5pt; text-transform: uppercase; letter-spacing: 1pt; color: #64748b; background: #f1f5f9; padding: 8px 10px; border-bottom: 1px solid #e2e8f0; }
        table.data th.right { text-align: right; }
        table.data td { padding: 8px 10px; border-bottom: 1px solid #f1f5f9; font-size: 10pt; color: #0f172a; }
        table.data td.right { text-align: right; font-weight: 600; }
        table.data tr:last-child td { border-bottom: none; }

        .footer { margin-top: 28px; padding-top: 12px; border-top: 1px solid #e5e7eb; color: #94a3b8; font-size: 8pt; text-align: center; }
    </style>
</head>
<body>
    <div class="band"></div>
    <div class="container">
        <table class="header">
            <tr>
                <td style="width: 60%;">
                    <div class="brand">{{ $shop->name }}</div>
                    <div class="brand-meta">
                        @if(!empty($shop->shop_code))Shop code: {{ $shop->shop_code }}@endif
                    </div>
                </td>
                <td style="width: 40%;" class="report-meta">
                    <div class="report-label">Report</div>
                    <div class="report-title">{{ $title }}</div>
                    <div class="report-range">
                        {{ $from->format('d M Y') }} – {{ $to->format('d M Y') }}
                    </div>
                </td>
            </tr>
        </table>

        @yield('content')

        <div class="footer">
            Generated by Rezzy · {{ now()->format('d M Y H:i') }}
        </div>
    </div>
</body>
</html>
